### ISSUE TITLE
Fehler bei der Generierung des og:description tags

### ISSUE THREAD

**Issue by chriza** [hofff-archive/contao-opengraph#8]
"<meta property="og:description" content"Saiso.........." />"
Es fehlt ein Gleichheitszeichen hinter dem Tag "content".

**Comment by backbone87** [comment]
kann ich nicht nachvollziehen. alle tags werden von der gleichen methode generiert:
https://github.com/hofff/contao-opengraph/blob/3.x/TL_ROOT/system/modules/backboneit_opengraph/OpenGraphProperty.php#L24

also müssten alle og meta tags betroffen sein und nicht nur die description.

bist du sicher das dieses tag von dieser erweiterung generiert wird und nicht durch andere erweiterungen die ebenfalls open graph daten anbieten oder von manuell eingetragen tags, z.B. im page layout

**Comment by frontendschlampe** [comment]
keine Rückmeldung mehr seit Monaten, deshalb geschlossen
